-- Posologies et contre-indications : catégorie fièvre (99 produits).
-- Ne remplit QUE les fiches encore vides : les 350 fiches déjà validées ne sont jamais écrasées.
-- Rédigé à partir de posologies usuelles ; les produits non identifiables reçoivent une consigne prudente.
BEGIN;
UPDATE medicines SET posologie = 'Adulte : 500 mg 3 fois par jour pendant les repas, pas plus de 7 jours (maximum 1 500 mg par jour). Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants.' -- Acide méfénamique
  WHERE id = '265c1533-1adf-4feb-8dd9-d9232a546566' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon la prescription médicale (la dose dépend de l''indication).', contre_indication = 'Antécédent de thrombose (phlébite, embolie), insuffisance rénale sévère, saignement urinaire, allergie.' -- Acide tranexamique
  WHERE id = '9ff90781-18c7-485b-ae1a-fc0ab932de53' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Actinac Plus cp
  WHERE id = 'b127bd16-a0d7-40ef-97f5-d06cdab2b763' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de 3 jours à suivre en entier, avec un repas ou une boisson grasse : 6 prises (au début, 8 h plus tard, puis matin et soir les jours 2 et 3). Nombre de comprimés selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie aux artémisinines ou à la luméfantrine, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque (QT long), paludisme grave (à traiter à l''hôpital) ; attention à l''association avec certains antirétroviraux et macrolides.' -- Acure 20/120 cp
  WHERE id = 'e5d3e968-c768-48a3-8e0a-cc116aaa2e32' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de 3 jours à suivre en entier, avec un repas ou une boisson grasse : 6 prises (au début, 8 h plus tard, puis matin et soir les jours 2 et 3). Nombre de comprimés selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie aux artémisinines ou à la luméfantrine, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque (QT long), paludisme grave (à traiter à l''hôpital) ; attention à l''association avec certains antirétroviraux et macrolides.' -- Acure 80/480 cp
  WHERE id = '19010dd1-1947-41d3-957e-79bd3b64dabd' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 200 à 400 mg par prise, 3 fois par jour maximum, pendant les repas, sur une courte durée (max 1 200 mg par jour sans avis médical). Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants. Varicelle.' -- Advil cp
  WHERE id = '7e8999bb-196a-414d-8599-6d86fe4728fd' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Enfant : 20 à 30 mg/kg par jour en 3 prises, avec la mesurette fournie, pendant les repas ; adapter au poids, demander conseil au pharmacien. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants. Varicelle ; enfant de moins de 3 mois.' -- Advil sp
  WHERE id = '6ccc805a-bea1-4fea-9cbf-57327f9e4ce7' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Antalgex T cp
  WHERE id = 'a0b2b388-99fe-449b-965b-f48d426bd1a4' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de 3 jours à suivre en entier, avec un repas ou une boisson grasse : 6 prises (au début, 8 h plus tard, puis matin et soir les jours 2 et 3). Nombre de comprimés selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie aux artémisinines ou à la luméfantrine, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque (QT long), paludisme grave (à traiter à l''hôpital) ; attention à l''association avec certains antirétroviraux et macrolides.' -- Arfacure 80/480 cp
  WHERE id = '0a74990a-e8d1-49f0-be2f-c2925f27b3a1' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de courte durée à suivre en entier, avec un repas. Dose selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie à l''un des composants, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque ; paludisme grave à traiter à l''hôpital.' -- Artésunate + sulfaméthopyrazine + pyriméthamine
  WHERE id = 'f723edcf-afe6-4db4-a62f-8ac7a0c8b69d' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de courte durée à suivre en entier, avec un repas. Dose selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie à l''un des composants, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque ; paludisme grave à traiter à l''hôpital.' -- Arther cp
  WHERE id = 'c93adbd7-b2f0-4b6e-8d78-0c7071a7f301' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de courte durée à suivre en entier, avec un repas. Dose selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie à l''un des composants, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque ; paludisme grave à traiter à l''hôpital.' -- Arther forte cp
  WHERE id = '0e0f0899-3ee6-4b9f-910d-564c3b053d44' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de 3 jours à suivre en entier, avec un repas ou une boisson grasse : 6 prises (au début, 8 h plus tard, puis matin et soir les jours 2 et 3). Nombre de comprimés selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie aux artémisinines ou à la luméfantrine, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque (QT long), paludisme grave (à traiter à l''hôpital) ; attention à l''association avec certains antirétroviraux et macrolides.' -- Artilex 80/480 cp
  WHERE id = '8b7467f6-7d8d-4007-876f-e85a9043176b' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de 3 jours à suivre en entier, avec un repas ou une boisson grasse : 6 prises (au début, 8 h plus tard, puis matin et soir les jours 2 et 3). Nombre de comprimés selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie aux artémisinines ou à la luméfantrine, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque (QT long), paludisme grave (à traiter à l''hôpital) ; attention à l''association avec certains antirétroviraux et macrolides.' -- Artrim 80/480 cp
  WHERE id = '7e88204f-a10c-4f29-803e-69c52fd14b77' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 500 mg à 1 g par prise dans un verre d''eau, à répéter si besoin après 4 à 6 heures, maximum 3 g par jour. Enfant de moins de 15 ans : uniquement sur avis médical.', contre_indication = 'Ulcère ou saignement, allergie à l''aspirine, asthme induit par les anti-inflammatoires, anticoagulants, grossesse à partir du 6e mois, enfant avec fièvre ou virose (risque de syndrome de Reye).' -- Aspegic sachet
  WHERE id = 'c978f120-af0c-484a-a380-4a3e9db821c9' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Asu-Denk cp
  WHERE id = '6fdf3174-098f-424d-b5d7-664a0afce01e' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Atopar 4 cp
  WHERE id = '0e739a84-b68b-40e0-95e7-0b315efead1d' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Atorox 20 cp
  WHERE id = '3a023ea8-d4b9-4f7f-ba40-43916f016ad7' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de courte durée à suivre en entier, avec un repas. Dose selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie à l''un des composants, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque ; paludisme grave à traiter à l''hôpital.' -- Bimalaril cp
  WHERE id = 'b5cc19f8-f26f-4a0d-aec1-7273a5f9ca88' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de courte durée à suivre en entier, avec un repas. Dose selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie à l''un des composants, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque ; paludisme grave à traiter à l''hôpital.' -- Bimalaril plus cp
  WHERE id = 'f8eb573f-4253-47e7-b6f2-223173f00a42' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 200 à 400 mg par prise, 3 fois par jour maximum, pendant les repas, sur une courte durée (max 1 200 mg par jour sans avis médical). Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants. Varicelle.' -- Brufen cp
  WHERE id = '1e69b1cc-df96-4204-b6d2-1e3b305e6843' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Enfant : 20 à 30 mg/kg par jour en 3 prises, avec la mesurette fournie, pendant les repas ; adapter au poids, demander conseil au pharmacien. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants. Varicelle ; enfant de moins de 3 mois.' -- Brufen sp
  WHERE id = 'e6c4bfba-af48-43df-9382-8ed89baa8cc9' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 200 mg par jour en 1 ou 2 prises, pendant un repas, sur prescription. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants. Allergie aux sulfamides ; maladie cardiovasculaire ou antécédent d''AVC.' -- Célécoxib
  WHERE id = 'a50b897e-db1a-4d4d-8a5a-7420bb6f65a4' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Cetamyl 1000mg cp
  WHERE id = '2d1591b1-e7fc-4f5d-b301-8474351d7b73' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Cetamyl sp
  WHERE id = '5824fb4b-71e6-4815-860d-82d5544afed7' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de courte durée à suivre en entier, avec un repas. Dose selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie à l''un des composants, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque ; paludisme grave à traiter à l''hôpital.' -- Co-Arinate Adulte cp
  WHERE id = '2cd0ef79-23a9-475c-a68e-14b90759518e' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de 3 jours à suivre en entier, avec un repas ou une boisson grasse : 6 prises (au début, 8 h plus tard, puis matin et soir les jours 2 et 3). Nombre de comprimés selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie aux artémisinines ou à la luméfantrine, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque (QT long), paludisme grave (à traiter à l''hôpital) ; attention à l''association avec certains antirétroviraux et macrolides.' -- Coartem Dispersible cp
  WHERE id = 'f90f1482-d5f8-47ec-b444-bef3ba5ddff7' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Uniquement sur prescription médicale : respecter la dose et l''intervalle indiqués sur l''ordonnance. Ne pas associer avec d''autres antalgiques opioïdes ni avec l''alcool.', contre_indication = 'Insuffisance respiratoire, insuffisance hépatique sévère, enfant de moins de 12 ans, allaitement, épilepsie non contrôlée (tramadol), alcool, association aux IMAO.' -- Co-Doliprane cp
  WHERE id = '33a929f5-b180-4edd-b63c-208e307f0686' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Diantalex cp
  WHERE id = '0da465b6-65bc-4db5-bc2d-b740eefbb0e7' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Dolex 75 cp
  WHERE id = 'e4aa9638-8dc7-40a3-864e-1405118d9597' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Dolimex 300mg sachet
  WHERE id = '5d1ce05e-18bc-473f-9d47-237b63e697d2' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Dolimex 500mg sachet
  WHERE id = '8b15aacb-287a-4391-a253-239c958a1015' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Dolimex effervescent cp
  WHERE id = '271f0634-65e2-477d-9eaf-567fde1378d8' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Dolimex Migraine cp
  WHERE id = '0901e397-7250-4cf6-ab2c-29dd4a545a05' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 1 comprimé (1 g) par prise, 3 fois par jour maximum, en espaçant d''au moins 6 heures. Ne pas dépasser 3 g par jour sans avis médical. Si la fièvre dure plus de 3 jours ou la douleur plus de 5 jours, consulter un médecin.', contre_indication = 'Allergie au paracétamol, insuffisance hépatique sévère. Ne pas associer avec un autre médicament contenant du paracétamol ; prudence avec l''alcool.' -- Doliprane 1000mg cp
  WHERE id = 'a9710eb7-a477-404c-9b4e-1156be1f0052' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Enfant : dose selon le poids (environ 15 mg/kg par prise), espacer de 4 à 6 heures, 4 prises maximum par jour ; demander le nombre exact au pharmacien. Si la fièvre dure plus de 3 jours ou la douleur plus de 5 jours, consulter un médecin.', contre_indication = 'Allergie au paracétamol, insuffisance hépatique sévère. Ne pas associer avec un autre médicament contenant du paracétamol ; prudence avec l''alcool.' -- Doliprane 200mg cp
  WHERE id = '45744fb1-d0b5-4ebb-8634-d42fa2bfe7e1' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Enfant : dose selon le poids (environ 15 mg/kg par prise), espacer de 4 à 6 heures, 4 prises maximum par jour ; demander le nombre exact au pharmacien. Si la fièvre dure plus de 3 jours ou la douleur plus de 5 jours, consulter un médecin.', contre_indication = 'Allergie au paracétamol, insuffisance hépatique sévère. Ne pas associer avec un autre médicament contenant du paracétamol ; prudence avec l''alcool.' -- Doliprane 300mg cp
  WHERE id = 'd8ef860e-da68-45b6-87d4-71bf2d7c5eb8' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 500 mg à 1 g par prise, toutes les 4 à 6 heures. Ne pas dépasser 3 g par jour sans avis médical. Enfant : selon le poids (environ 15 mg/kg par prise). Si la fièvre dure plus de 3 jours ou la douleur plus de 5 jours, consulter un médecin.', contre_indication = 'Allergie au paracétamol, insuffisance hépatique sévère. Ne pas associer avec un autre médicament contenant du paracétamol ; prudence avec l''alcool.' -- Doliprane sec cp
  WHERE id = '62d115d9-dfdd-4c5b-899f-1e6d138dedbe' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 60 à 90 mg une fois par jour, sur prescription, cure courte. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants. Hypertension non contrôlée, maladie cardiovasculaire.' -- Étoricoxib
  WHERE id = '5eef6c99-adbd-4721-ba1c-d102ad87c310' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Exxib cp
  WHERE id = 'a625a3a4-d410-4635-ae61-0d70dad1862e' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 20 mg une fois par jour pendant un repas, cure courte. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants.' -- Feldene cp
  WHERE id = '61c61f2b-8028-405c-bb0b-7b3ea8bfa80d' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 50 à 100 mg 2 à 3 fois par jour pendant les repas, maximum 300 mg par jour, cure courte. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants.' -- Flurbiprofène
  WHERE id = '7ed17a19-eff3-42e8-b33d-35301168e3e2' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Ib Artefan sp
  WHERE id = 'ef9bf37c-145c-4cc9-9ae2-3119733e332d' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 200 à 400 mg par prise, 3 fois par jour maximum, pendant les repas, sur une courte durée (max 1 200 mg par jour sans avis médical). Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants. Varicelle.' -- Ibex cp
  WHERE id = '04dd1031-567e-4382-b5c2-44a9ea3dd463' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 200 à 400 mg par prise, 3 fois par jour maximum, pendant les repas, sur une courte durée (max 1 200 mg par jour sans avis médical). Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants. Varicelle.' -- Ibumol cp
  WHERE id = '938d9a1d-7c8d-47c8-b61f-ecbff662e25d' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Enfant : 20 à 30 mg/kg par jour en 3 prises, avec la mesurette fournie, pendant les repas ; adapter au poids, demander conseil au pharmacien. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants. Varicelle ; enfant de moins de 3 mois.' -- Ibumol sp
  WHERE id = '060f4acc-4124-496b-bde3-6ac75cde52ea' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 50 mg 2 à 3 fois par jour ou 100 mg 2 fois par jour pendant les repas, maximum 200 mg par jour, cure courte. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants.' -- Kétoprofène
  WHERE id = '249f2ac1-2115-458e-a200-a75ac04fca7d' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 50 mg 2 à 3 fois par jour ou 100 mg 2 fois par jour pendant les repas, maximum 200 mg par jour, cure courte. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants.' -- Ketoprofen-GH-100 cp
  WHERE id = '130f41d2-3ef7-4016-b703-a5127d252969' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Uniquement sur prescription médicale : respecter la dose et l''intervalle indiqués sur l''ordonnance. Ne pas associer avec d''autres antalgiques opioïdes ni avec l''alcool.', contre_indication = 'Insuffisance respiratoire, insuffisance hépatique sévère, enfant de moins de 12 ans, allaitement, épilepsie non contrôlée (tramadol), alcool, association aux IMAO.' -- Klipal cp
  WHERE id = '0cc10808-9958-4efc-a173-3104f8b76c31' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Lidocaïne
  WHERE id = '271e9ae0-b5dd-42be-9ce3-db3d2e6952a4' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Litamol cp
  WHERE id = '59108b85-cc5b-4d90-b1d9-0f907bcc4ffe' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Lofnac 100 cp
  WHERE id = 'c0d684b0-6afc-4a82-bcd5-67d543cfa017' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Appliquer une fine couche 2 à 3 fois par jour sur la zone douloureuse, masser légèrement, se laver les mains après usage. Cure courte.', contre_indication = 'Allergie, peau lésée ou plaie, muqueuses et yeux, pansement fermé ; éviter l''exposition au soleil sur la zone traitée ; grossesse : avis médical.' -- Lofnac creme
  WHERE id = '49cd4f69-4eba-4cf5-8f64-3772600bf5e6' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de courte durée à suivre en entier, avec un repas. Dose selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie à l''un des composants, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque ; paludisme grave à traiter à l''hôpital.' -- Lufamet-DS cp
  WHERE id = 'bc1adde9-fdcf-4c5b-9f69-bc3ab0f9bebb' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de courte durée à suivre en entier, avec un repas. Dose selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie à l''un des composants, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque ; paludisme grave à traiter à l''hôpital.' -- Maloxine cp
  WHERE id = 'd5dfa542-0912-43f3-8f39-7c130bd6256c' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 7,5 à 15 mg une fois par jour pendant un repas, cure courte. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants.' -- Méloxicam
  WHERE id = '6a890fe6-edfe-4090-afcc-c082c630ad4b' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Mobitil cp
  WHERE id = '5c64020c-7178-42d1-84a2-919f30059aa8' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Muscurel cp
  WHERE id = '68ac4e2d-41e4-4e4b-9917-36a50e8a2e60' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 500 mg à 1 g par prise, jusqu''à 4 fois par jour selon prescription, maximum 4 g par jour.', contre_indication = 'Antécédent d''agranulocytose, allergie aux pyrazolés ou aux anti-inflammatoires, porphyrie, déficit en G6PD, grossesse (3e trimestre), allaitement ; peut faire baisser la tension.' -- Novalgin 500mg cp
  WHERE id = '4553baf3-6028-4a74-b023-e7940e3eb797' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de 3 jours à suivre en entier, avec un repas ou une boisson grasse : 6 prises (au début, 8 h plus tard, puis matin et soir les jours 2 et 3). Nombre de comprimés selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie aux artémisinines ou à la luméfantrine, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque (QT long), paludisme grave (à traiter à l''hôpital) ; attention à l''association avec certains antirétroviraux et macrolides.' -- Palucure 80/480 cp
  WHERE id = 'fd75252e-15b3-47e0-b07c-bf7943875765' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Enfant : environ 15 mg/kg par prise avec la mesurette fournie, toutes les 6 heures, 4 prises maximum par jour. Adapter au poids, demander conseil au pharmacien. Si la fièvre dure plus de 3 jours ou la douleur plus de 5 jours, consulter un médecin.', contre_indication = 'Allergie au paracétamol, insuffisance hépatique sévère. Ne pas associer avec un autre médicament contenant du paracétamol ; prudence avec l''alcool.' -- Panadol sp
  WHERE id = '1aaeecaa-0f21-43fb-85bf-7be82f46b63a' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Panalgic cp
  WHERE id = 'b9ae6ea0-d268-407b-98c4-987ad44e3fc5' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 1 comprimé (500 mg), à répéter si besoin toutes les 4 à 6 heures, jusqu''à 4 par jour. Ne pas dépasser 3 g par jour sans avis médical. Si la fièvre dure plus de 3 jours ou la douleur plus de 5 jours, consulter un médecin.', contre_indication = 'Allergie au paracétamol, insuffisance hépatique sévère. Ne pas associer avec un autre médicament contenant du paracétamol ; prudence avec l''alcool.' -- Panodol 500mg cp
  WHERE id = 'bab83cec-86fd-4d43-b375-ee4b752a9695' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 500 mg à 1 g par prise, toutes les 4 à 6 heures. Ne pas dépasser 3 g par jour sans avis médical. Enfant : selon le poids (environ 15 mg/kg par prise). Si la fièvre dure plus de 3 jours ou la douleur plus de 5 jours, consulter un médecin.', contre_indication = 'Allergie au paracétamol, insuffisance hépatique sévère. Ne pas associer avec un autre médicament contenant du paracétamol ; prudence avec l''alcool.' -- Paracetamol creme
  WHERE id = '7f257292-0702-4b6b-bb17-a1f45df9849b' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Uniquement sur prescription médicale : respecter la dose et l''intervalle indiqués sur l''ordonnance. Ne pas associer avec d''autres antalgiques opioïdes ni avec l''alcool.', contre_indication = 'Insuffisance respiratoire, insuffisance hépatique sévère, enfant de moins de 12 ans, allaitement, épilepsie non contrôlée (tramadol), alcool, association aux IMAO.' -- Paraco-Denk 500-30 cp
  WHERE id = '4088c207-c4e8-4396-8f87-ac037d04d1f6' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 500 mg à 1 g par prise, toutes les 4 à 6 heures. Ne pas dépasser 3 g par jour sans avis médical. Enfant : selon le poids (environ 15 mg/kg par prise). Si la fièvre dure plus de 3 jours ou la douleur plus de 5 jours, consulter un médecin.', contre_indication = 'Allergie au paracétamol, insuffisance hépatique sévère. Ne pas associer avec un autre médicament contenant du paracétamol ; prudence avec l''alcool.' -- Paradex cp
  WHERE id = 'a6ca14ea-aaed-41c5-90ba-5029615e7867' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 500 mg à 1 g par prise, toutes les 4 à 6 heures. Ne pas dépasser 3 g par jour sans avis médical. Enfant : selon le poids (environ 15 mg/kg par prise). Si la fièvre dure plus de 3 jours ou la douleur plus de 5 jours, consulter un médecin.', contre_indication = 'Allergie au paracétamol, insuffisance hépatique sévère. Ne pas associer avec un autre médicament contenant du paracétamol ; prudence avec l''alcool.' -- Paradik forte cp
  WHERE id = '2fc21343-8ebf-4444-bcd8-20c5558f2588' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 500 mg à 1 g par prise, toutes les 4 à 6 heures. Ne pas dépasser 3 g par jour sans avis médical. Enfant : selon le poids (environ 15 mg/kg par prise). Si la fièvre dure plus de 3 jours ou la douleur plus de 5 jours, consulter un médecin.', contre_indication = 'Allergie au paracétamol, insuffisance hépatique sévère. Ne pas associer avec un autre médicament contenant du paracétamol ; prudence avec l''alcool.' -- Parol cp
  WHERE id = '092e5528-474d-4533-85f5-38a3c034189c' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 50 mg 2 à 3 fois par jour pendant les repas (forme à libération prolongée : 1 fois par jour), cure courte, maximum 150 mg par jour. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants.' -- Philco Diclo 50 cp
  WHERE id = 'c97f2529-e86b-45b4-8e89-6f04c6b98d66' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 200 à 400 mg par prise, 3 fois par jour maximum, pendant les repas, sur une courte durée (max 1 200 mg par jour sans avis médical). Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants. Varicelle.' -- Philco Ibuprofen cp
  WHERE id = '059adfd6-3f94-4f50-88b5-fdda480410bc' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 500 mg à 1 g par prise, toutes les 4 à 6 heures. Ne pas dépasser 3 g par jour sans avis médical. Enfant : selon le poids (environ 15 mg/kg par prise). Si la fièvre dure plus de 3 jours ou la douleur plus de 5 jours, consulter un médecin.', contre_indication = 'Allergie au paracétamol, insuffisance hépatique sévère. Ne pas associer avec un autre médicament contenant du paracétamol ; prudence avec l''alcool.' -- Philco Para cp
  WHERE id = '3e36af18-6b0e-4c27-a752-40304f76a66e' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Uniquement sur prescription et administration par un professionnel de santé.', contre_indication = 'Allergie à la quinine, troubles du rythme cardiaque (QT long), névrite optique, myasthénie, déficit en G6PD.' -- Philco Quinine injectable
  WHERE id = '21f3a03b-0ad1-42ae-bd4f-b583d30c1c63' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Picloxa 500 cp
  WHERE id = '786fab3e-4e51-4882-b416-82d324f50ebf' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 20 mg une fois par jour pendant un repas, cure courte. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants.' -- Piroxicam
  WHERE id = 'a52a110f-679d-4d07-8d60-1020effcf1ad' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Traitement de courte durée à suivre en entier, avec un repas. Dose selon le poids et l''âge : selon l''ordonnance ou l''avis du pharmacien.', contre_indication = 'Allergie à l''un des composants, 1er trimestre de grossesse (sauf avis médical), troubles du rythme cardiaque ; paludisme grave à traiter à l''hôpital.' -- Plasmocur 80/640 cp
  WHERE id = 'afbd5936-5916-48a2-9b7e-8c2404c6ea2d' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 200 mg par jour en 1 ou 2 prises, pendant un repas, sur prescription. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants. Allergie aux sulfamides ; maladie cardiovasculaire ou antécédent d''AVC.' -- Plencoxib-200 cp
  WHERE id = '896ffe9b-884a-4782-add5-d519a98b4d82' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Profenol cp
  WHERE id = '48ad4b43-0ce2-4358-aec4-90bd1e8dd8fe' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Profenol sp
  WHERE id = 'e82eb910-558e-4355-b3aa-d2c6563032f7' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Reumoxican cp
  WHERE id = '661691b4-2ce9-44bc-b394-b71813a4e315' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Ribatran cp
  WHERE id = 'e42f16a3-86da-4e6e-b36f-ce73f1b28847' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Roipar 1000 cp
  WHERE id = 'dac2b5e0-6d36-4636-873e-56d9eafc6529' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Roipar 500 cp
  WHERE id = 'b0fa3042-9a52-4af2-900a-531f98631101' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Roipar Grippe cp
  WHERE id = '1db376e5-726d-4812-8b61-65c3ce6c7c19' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Roipar sp
  WHERE id = '3ac248b4-77aa-492d-bcbf-a5ef6adfa363' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Sekalgic cp
  WHERE id = 'a77f544c-49d1-4b62-a72f-5f2d2e0c6c2d' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Stopadol cp
  WHERE id = '0d12c287-7275-4342-bbc0-2948e0319ee4' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- T-Bol P Rapid cp
  WHERE id = '4a174f0c-e2a0-4427-bab9-9c2067f926f5' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Uniquement sur prescription médicale : respecter la dose et l''intervalle indiqués sur l''ordonnance. Ne pas associer avec d''autres antalgiques opioïdes ni avec l''alcool.', contre_indication = 'Insuffisance respiratoire, insuffisance hépatique sévère, enfant de moins de 12 ans, allaitement, épilepsie non contrôlée (tramadol), alcool, association aux IMAO.' -- Tramadol + paracétamol
  WHERE id = 'bc4baaf8-519f-44e1-92d4-f3949a766ba9' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Trialgic cp
  WHERE id = 'd2f21e9e-2021-4bf4-a1b1-920074159ed3' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 50 mg 2 à 3 fois par jour pendant les repas (forme à libération prolongée : 1 fois par jour), cure courte, maximum 150 mg par jour. Prendre la dose efficace la plus faible, le moins longtemps possible ; consulter si pas d''amélioration après 3 jours.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants.' -- TroyFenac MR cp
  WHERE id = 'bf95493e-a656-4bbf-9a82-e02d30512ce9' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Appliquer une fine couche 2 à 3 fois par jour sur la zone douloureuse, masser légèrement, se laver les mains après usage. Cure courte.', contre_indication = 'Allergie, peau lésée ou plaie, muqueuses et yeux, pansement fermé ; éviter l''exposition au soleil sur la zone traitée ; grossesse : avis médical.' -- Vegebom creme chauffant
  WHERE id = 'daa8c496-599e-4ed5-909c-6bc13e903a6b' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Appliquer une fine couche 2 à 3 fois par jour sur la zone douloureuse, masser légèrement, se laver les mains après usage. Cure courte.', contre_indication = 'Allergie, peau lésée ou plaie, muqueuses et yeux, pansement fermé ; éviter l''exposition au soleil sur la zone traitée ; grossesse : avis médical.' -- Vegebom creme non chauffant
  WHERE id = '70cd2b2b-25af-4057-a87f-07950f87c511' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Appliquer une fine couche 2 à 3 fois par jour sur la zone douloureuse, masser légèrement, se laver les mains après usage. Cure courte.', contre_indication = 'Allergie, peau lésée ou plaie, muqueuses et yeux, pansement fermé ; éviter l''exposition au soleil sur la zone traitée ; grossesse : avis médical.' -- Volini creme
  WHERE id = 'df7416f0-b709-4646-bb06-d6c312491e03' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Appliquer une fine couche 2 à 3 fois par jour sur la zone douloureuse, masser légèrement, se laver les mains après usage. Cure courte.', contre_indication = 'Allergie, peau lésée ou plaie, muqueuses et yeux, pansement fermé ; éviter l''exposition au soleil sur la zone traitée ; grossesse : avis médical.' -- Voltarene creme
  WHERE id = 'a2e42d26-0480-4f33-a202-5aad6481d871' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Appliquer une fine couche 2 à 3 fois par jour sur la zone douloureuse, masser légèrement, se laver les mains après usage. Cure courte.', contre_indication = 'Allergie, peau lésée ou plaie, muqueuses et yeux, pansement fermé ; éviter l''exposition au soleil sur la zone traitée ; grossesse : avis médical.' -- Voxgel creme
  WHERE id = '3f36b906-e7da-4c10-a145-dced70d17fbd' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Selon l''ordonnance ou l''avis du pharmacien. Respecter la dose et la durée indiquées sur la notice ; ne pas dépasser la dose prescrite.', contre_indication = 'Allergie à l''un des composants. Grossesse, allaitement, enfant, maladie du foie, du rein ou du cœur : demander conseil au pharmacien avant usage.' -- Xykaa cp
  WHERE id = '64f3179c-d4dc-4906-aff7-d4a1be8fb505' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Uniquement sur prescription médicale : respecter la dose et l''intervalle indiqués sur l''ordonnance. Ne pas associer avec d''autres antalgiques opioïdes ni avec l''alcool.', contre_indication = 'Insuffisance respiratoire, insuffisance hépatique sévère, enfant de moins de 12 ans, allaitement, épilepsie non contrôlée (tramadol), alcool, association aux IMAO.' -- Zamudol LP 50 cp
  WHERE id = '68381855-c4d5-4353-a535-cb6e4132aa5f' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 1 comprimé par jour, pendant un repas, cure courte.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants.' -- Zerodol-CR cp
  WHERE id = '056075e9-c169-4133-b179-d6ec27b6e369' AND (posologie IS NULL OR posologie = '');
UPDATE medicines SET posologie = 'Adulte : 1 comprimé 2 fois par jour, pendant les repas, cure courte. Ne pas associer avec un autre médicament contenant du paracétamol.', contre_indication = 'Ulcère ou saignement digestif, insuffisance rénale, cardiaque ou hépatique sévère, allergie à l''aspirine ou aux anti-inflammatoires, grossesse à partir du 6e mois ; prudence avec les anticoagulants. Ne pas associer avec un autre produit à base de paracétamol.' -- Zerodol P cp
  WHERE id = 'ca5abbd3-569b-46af-b0bc-6efff3234ca2' AND (posologie IS NULL OR posologie = '');
SELECT count(*) AS fiches_sans_posologie_restantes FROM medicines WHERE category = 'fievre' AND (posologie IS NULL OR posologie = '');
COMMIT;
